#!/usr/bin/env python3
"""Regenerates screwdriver-sd5-340.urdf from botrail's own tool builder.

The asset *is* `bt.tools.screwdriver_urdf(...)` with the SD5-340 figures
below, written out — so the catalogued screwdriver and the one a cell
builds in Python are the same envelope to the millimetre. Re-run after
changing a figure, then commit the URDF.

    python tools/generate_urdf.py            # writes ../urdf/screwdriver-sd5-340.urdf
"""

from pathlib import Path

import botrail as bt

# The reference envelope (metres): a cobot screwdriver's public figures —
# 308 mm long overall, 86 mm across, a 55 mm shank stroke — as a body,
# a nose and a bit that add up to that length. See ../README.md.
FIGURES = dict(
    body_length=0.200,
    body_diameter=0.086,
    nose_length=0.050,
    nose_diameter=0.030,
    bit_length=0.060,
    bit_diameter=0.008,
    stroke=0.055,
)


def main() -> None:
    out = Path(__file__).resolve().parents[1] / "urdf" / "screwdriver-sd5-340.urdf"
    header = (
        "<!--\n"
        "  SD5-340 screwdriver envelope: the motor body, the nose and the bit on the\n"
        "  tool's own stroke (CC0-1.0, botrail-assets). Generated by\n"
        "  tools/generate_urdf.py from bt.tools.screwdriver_urdf — edit the figures\n"
        "  there, not here.\n"
        "\n"
        "  Frames (botrail catalog convention, Z-up, metres):\n"
        "    mount   root = the face that bolts to the hand (ISO 9409-1-50-4-M6), +Z into the tool\n"
        "    body    the motor housing, a cylinder along the axis\n"
        "    nose    the front housing the bit runs out of\n"
        "    bit     the bit, on the prismatic joint `shank` (0 to 55 mm along the axis)\n"
        "    tip     the bit's free end, turned half a turn about X: +Z back along the tool\n"
        "-->\n"
    )
    text = bt.tools.screwdriver_urdf(**FIGURES)
    text = text.replace('<?xml version="1.0"?>\n', '<?xml version="1.0"?>\n' + header, 1)
    out.write_text(text, encoding="utf-8")
    print(f"wrote {out}")


if __name__ == "__main__":
    main()
