#!/usr/bin/env python3
"""Regenerates multi-hand-mph3.urdf from botrail's own hand builder.

The asset *is* `bt.tools.multi_tool_urdf("mph3", ...)` with the MPH-3
layout below, written out — so the catalogued hand and the one a cell
builds in Python are the same geometry to the millimetre. Re-run after
changing the layout, then commit the URDF.

    python tools/generate_urdf.py            # writes ../urdf/multi-hand-mph3.urdf
"""

from pathlib import Path

import botrail as bt

# The MPH-3 layout (metres, in the plate frame: +Z out of the robot flange).
NAME = "mph3"
PLATE = (0.080, 0.012)                 # ISO 9409-1-50 sized plate, 12 mm thick
TOOLS = [
    bt.tools.Mount("gripper"),                                   # the gripper stack, down the axis
    bt.tools.Pin("pusher", length=0.060, diameter=0.012,
                 at=(0.040, 0.0, 0.022), direction=(1.0, 0.0, 0.0)),   # the button pin, out +X
    bt.tools.Fork("fork", reach=0.080, gap=0.030, prong=0.010, seat=0.050,
                  at=(-0.040, 0.0, 0.022), direction=(-1.0, 0.0, 0.0),
                  across=(0.0, 1.0, 0.0)),                       # the door fork, out -X
]


def main() -> None:
    out = Path(__file__).resolve().parents[1] / "urdf" / "multi-hand-mph3.urdf"
    header = (
        "<!--\n"
        "  MPH-3 multi-purpose hand: a flange plate carrying a gripper mount, a\n"
        "  button pin and a door fork (CC0-1.0, botrail-assets). Generated by\n"
        "  tools/generate_urdf.py from bt.tools.multi_tool_urdf — edit the\n"
        "  layout there, not here.\n"
        "\n"
        "  Frames (botrail catalog convention, Z-up, metres):\n"
        "    mph3_plate        root = the robot flange face (ISO 9409-1-50-4-M6), +Z outward\n"
        "    mph3_gripper      the face the gripper stack bolts to, 12 mm out along +Z\n"
        "    mph3_pusher_tip   the pin's end, +Z along the pin (+X of the plate, 100 mm out)\n"
        "    mph3_fork_tip     the seat between the prongs, +Z along them (-X of the plate)\n"
        "-->\n"
    )
    text = bt.tools.multi_tool_urdf(NAME, TOOLS, plate=PLATE)
    text = text.replace('<?xml version="1.0"?>\n', '<?xml version="1.0"?>\n' + header, 1)
    out.write_text(text, encoding="utf-8")
    print(f"wrote {out}")


if __name__ == "__main__":
    main()
