import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {definition,D} from './model.mjs';import {urdf,meshFiles as rawMeshFiles} from '../../authoring/reference-export.mjs';
import {meshFiles,compactObj} from './compact-obj.mjs';
const base=new URL('./kinematics-baseline.json',import.meta.url);
const contract=d=>({name:d.name,links:d.links.map(({name,collisions})=>({name,...(collisions?{collisions}: {})})),joints:d.joints});
test('main fixed frames and collision contract are unchanged',()=>assert.deepEqual(contract(definition()),JSON.parse(fs.readFileSync(base))))
test('URDF and all generated meshes are deterministic',()=>{const a=definition(),b=definition();assert.equal(urdf(a),urdf(b));const files=meshFiles(a.links);assert.deepEqual(files,meshFiles(b.links));for(const [p,t]of Object.entries(files))assert.equal(t,fs.readFileSync(new URL('../'+p,import.meta.url),'utf8'));assert.equal(urdf(a),fs.readFileSync(new URL('../urdf/piab-picobot.urdf',import.meta.url),'utf8'));});
test('cup spacing, contact plane, topology hierarchy and no invented motion',()=>{const d=definition();assert.equal(D.cupSpacing,.120);assert.equal(d.joints.length,5);assert.ok(d.joints.every(j=>j.type==='fixed'));assert.equal(d.joints.find(j=>j.name==='tcp_joint').xyz[2],.134);for(const n of ['cup_a','cup_b']){let lo=Infinity,hi=-Infinity;d.links.find(l=>l.name===n).visual.updateMatrixWorld(true);d.links.find(l=>l.name===n).visual.traverse(o=>{if(!o.isMesh)return;const a=o.geometry.attributes.position;for(let i=0;i<a.count;i++){const v=o.localToWorld(o.position.clone().set(a.getX(i),a.getY(i),a.getZ(i)));lo=Math.min(lo,v.z);hi=Math.max(hi,v.z);}});assert.ok(Math.abs(lo)<1e-8);assert.ok(Math.abs(hi-.022)<1e-8);}});
test('part names unique, finite geometry and both opposite-side vacuum tubes',()=>{const d=definition();for(const l of d.links){const names=new Set();l.visual?.traverse(o=>{if(!o.isMesh)return;assert.ok(!names.has(o.name),o.name);names.add(o.name);assert.ok(/^[A-Za-z0-9_.-]+$/.test(o.name));for(const x of o.geometry.attributes.position.array)assert.ok(Number.isFinite(x));});}const b=d.links[0].visual;assert.ok(b.getObjectByName('vacuum_tube_a').position.y<0);assert.ok(b.getObjectByName('vacuum_tube_b').position.y>0);});
function expanded(s){const vs={v:[],vt:[],vn:[]};return s.split('\n').flatMap(l=>{const m=/^(v|vt|vn) (.*)/.exec(l);if(m){vs[m[1]].push(m[2]);return [];}if(l.startsWith('f '))return ['f '+l.slice(2).split(' ').map(t=>t.split('/').map((n,i)=>n?vs[['v','vt','vn'][i]][Number(n)-1]:'').join('|')).join(';')];return [l];});}
test('lossless compaction preserves each triangle corner, normals, UV, material and object',()=>{for(const [p,t]of Object.entries(rawMeshFiles(definition().links)))if(p.endsWith('.obj'))assert.deepEqual(expanded(t),expanded(compactObj(t)));});
test('generated blobs remain under Git Data body budget',()=>{for(const [p,t]of Object.entries(meshFiles(definition().links)))assert.ok(Buffer.byteLength(t)*4/3+2048<16*1024*1024,p);});
